version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando Serverless Framework"
      - npm install -g serverless
      - echo "Instalando dependencias del proyecto"
      - npm install

  build:
    commands:
      - echo "Empaquetando e implementando con Serverless"
      - serverless deploy --region sa-east-1

  post_build:
    commands:
      - echo "Despliegue completado"
      - echo "Obteniendo la URL del endpoint si aplica"
      - serverless info --region sa-east-1

artifacts:
  files:
    - '**/*'
