service: aws-node-http-api-project
frameworkVersion: '3.38.0'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  stage: dev
  deploymentBucket:
    name: my-serverless-deploy-bucket-sa-east-1 # <== personalízalo

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
